-- ISO 3166-1 alpha-2 codes and country names
-- Flag URLs using flagcdn.com (w320 size for good quality)

INSERT INTO countries (name, code, flag_url) VALUES
('Afghanistan', 'AF', 'https://flagcdn.com/w320/af.png'),
('Albania', 'AL', 'https://flagcdn.com/w320/al.png'),
('Algeria', 'DZ', 'https://flagcdn.com/w320/dz.png'),
('Andorra', 'AD', 'https://flagcdn.com/w320/ad.png'),
('Angola', 'AO', 'https://flagcdn.com/w320/ao.png'),
('Antigua and Barbuda', 'AG', 'https://flagcdn.com/w320/ag.png'),
('Argentina', 'AR', 'https://flagcdn.com/w320/ar.png'),
('Armenia', 'AM', 'https://flagcdn.com/w320/am.png'),
('Australia', 'AU', 'https://flagcdn.com/w320/au.png'),
('Austria', 'AT', 'https://flagcdn.com/w320/at.png'),
('Azerbaijan', 'AZ', 'https://flagcdn.com/w320/az.png'),
('Bahamas', 'BS', 'https://flagcdn.com/w320/bs.png'),
('Bahrain', 'BH', 'https://flagcdn.com/w320/bh.png'),
('Bangladesh', 'BD', 'https://flagcdn.com/w320/bd.png'),
('Barbados', 'BB', 'https://flagcdn.com/w320/bb.png'),
('Belarus', 'BY', 'https://flagcdn.com/w320/by.png'),
('Belgium', 'BE', 'https://flagcdn.com/w320/be.png'),
('Belize', 'BZ', 'https://flagcdn.com/w320/bz.png'),
('Benin', 'BJ', 'https://flagcdn.com/w320/bj.png'),
('Bhutan', 'BT', 'https://flagcdn.com/w320/bt.png'),
('Bolivia', 'BO', 'https://flagcdn.com/w320/bo.png'),
('Bosnia and Herzegovina', 'BA', 'https://flagcdn.com/w320/ba.png'),
('Botswana', 'BW', 'https://flagcdn.com/w320/bw.png'),
('Brazil', 'BR', 'https://flagcdn.com/w320/br.png'),
('Brunei', 'BN', 'https://flagcdn.com/w320/bn.png'),
('Bulgaria', 'BG', 'https://flagcdn.com/w320/bg.png'),
('Burkina Faso', 'BF', 'https://flagcdn.com/w320/bf.png'),
('Burundi', 'BI', 'https://flagcdn.com/w320/bi.png'),
('Cabo Verde', 'CV', 'https://flagcdn.com/w320/cv.png'),
('Cambodia', 'KH', 'https://flagcdn.com/w320/kh.png'),
('Cameroon', 'CM', 'https://flagcdn.com/w320/cm.png'),
('Canada', 'CA', 'https://flagcdn.com/w320/ca.png'),
('Central African Republic', 'CF', 'https://flagcdn.com/w320/cf.png'),
('Chad', 'TD', 'https://flagcdn.com/w320/td.png'),
('Chile', 'CL', 'https://flagcdn.com/w320/cl.png'),
('China', 'CN', 'https://flagcdn.com/w320/cn.png'),
('Colombia', 'CO', 'https://flagcdn.com/w320/co.png'),
('Comoros', 'KM', 'https://flagcdn.com/w320/km.png'),
('Congo (Democratic Republic of the)', 'CD', 'https://flagcdn.com/w320/cd.png'),
('Congo (Republic of the)', 'CG', 'https://flagcdn.com/w320/cg.png'),
('Costa Rica', 'CR', 'https://flagcdn.com/w320/cr.png'),
('Croatia', 'HR', 'https://flagcdn.com/w320/hr.png'),
('Cuba', 'CU', 'https://flagcdn.com/w320/cu.png'),
('Cyprus', 'CY', 'https://flagcdn.com/w320/cy.png'),
('Czech Republic', 'CZ', 'https://flagcdn.com/w320/cz.png'),
('Denmark', 'DK', 'https://flagcdn.com/w320/dk.png'),
('Djibouti', 'DJ', 'https://flagcdn.com/w320/dj.png'),
('Dominica', 'DM', 'https://flagcdn.com/w320/dm.png'),
('Dominican Republic', 'DO', 'https://flagcdn.com/w320/do.png'),
('East Timor', 'TL', 'https://flagcdn.com/w320/tl.png'),
('Ecuador', 'EC', 'https://flagcdn.com/w320/ec.png'),
('Egypt', 'EG', 'https://flagcdn.com/w320/eg.png'),
('El Salvador', 'SV', 'https://flagcdn.com/w320/sv.png'),
('Equatorial Guinea', 'GQ', 'https://flagcdn.com/w320/gq.png'),
('Eritrea', 'ER', 'https://flagcdn.com/w320/er.png'),
('Estonia', 'EE', 'https://flagcdn.com/w320/ee.png'),
('Eswatini', 'SZ', 'https://flagcdn.com/w320/sz.png'),
('Ethiopia', 'ET', 'https://flagcdn.com/w320/et.png'),
('Fiji', 'FJ', 'https://flagcdn.com/w320/fj.png'),
('Finland', 'FI', 'https://flagcdn.com/w320/fi.png'),
('France', 'FR', 'https://flagcdn.com/w320/fr.png'),
('Gabon', 'GA', 'https://flagcdn.com/w320/ga.png'),
('Gambia', 'GM', 'https://flagcdn.com/w320/gm.png'),
('Georgia', 'GE', 'https://flagcdn.com/w320/ge.png'),
('Germany', 'DE', 'https://flagcdn.com/w320/de.png'),
('Ghana', 'GH', 'https://flagcdn.com/w320/gh.png'),
('Greece', 'GR', 'https://flagcdn.com/w320/gr.png'),
('Grenada', 'GD', 'https://flagcdn.com/w320/gd.png'),
('Guatemala', 'GT', 'https://flagcdn.com/w320/gt.png'),
('Guinea', 'GN', 'https://flagcdn.com/w320/gn.png'),
('Guinea-Bissau', 'GW', 'https://flagcdn.com/w320/gw.png'),
('Guyana', 'GY', 'https://flagcdn.com/w320/gy.png'),
('Haiti', 'HT', 'https://flagcdn.com/w320/ht.png'),
('Honduras', 'HN', 'https://flagcdn.com/w320/hn.png'),
('Hungary', 'HU', 'https://flagcdn.com/w320/hu.png'),
('Iceland', 'IS', 'https://flagcdn.com/w320/is.png'),
('India', 'IN', 'https://flagcdn.com/w320/in.png'),
('Indonesia', 'ID', 'https://flagcdn.com/w320/id.png'),
('Iran', 'IR', 'https://flagcdn.com/w320/ir.png'),
('Iraq', 'IQ', 'https://flagcdn.com/w320/iq.png'),
('Ireland', 'IE', 'https://flagcdn.com/w320/ie.png'),
('Israel', 'IL', 'https://flagcdn.com/w320/il.png'),
('Italy', 'IT', 'https://flagcdn.com/w320/it.png'),
('Ivory Coast', 'CI', 'https://flagcdn.com/w320/ci.png'),
('Jamaica', 'JM', 'https://flagcdn.com/w320/jm.png'),
('Japan', 'JP', 'https://flagcdn.com/w320/jp.png'),
('Jordan', 'JO', 'https://flagcdn.com/w320/jo.png'),
('Kazakhstan', 'KZ', 'https://flagcdn.com/w320/kz.png'),
('Kenya', 'KE', 'https://flagcdn.com/w320/ke.png'),
('Kiribati', 'KI', 'https://flagcdn.com/w320/ki.png'),
('Korea (North)', 'KP', 'https://flagcdn.com/w320/kp.png'),
('Korea (South)', 'KR', 'https://flagcdn.com/w320/kr.png'),
('Kosovo', 'XK', 'https://flagcdn.com/w320/xk.png'),
('Kuwait', 'KW', 'https://flagcdn.com/w320/kw.png'),
('Kyrgyzstan', 'KG', 'https://flagcdn.com/w320/kg.png'),
('Laos', 'LA', 'https://flagcdn.com/w320/la.png'),
('Latvia', 'LV', 'https://flagcdn.com/w320/lv.png'),
('Lebanon', 'LB', 'https://flagcdn.com/w320/lb.png'),
('Lesotho', 'LS', 'https://flagcdn.com/w320/ls.png'),
('Liberia', 'LR', 'https://flagcdn.com/w320/lr.png'),
('Libya', 'LY', 'https://flagcdn.com/w320/ly.png'),
('Liechtenstein', 'LI', 'https://flagcdn.com/w320/li.png'),
('Lithuania', 'LT', 'https://flagcdn.com/w320/lt.png'),
('Luxembourg', 'LU', 'https://flagcdn.com/w320/lu.png'),
('Madagascar', 'MG', 'https://flagcdn.com/w320/mg.png'),
('Malawi', 'MW', 'https://flagcdn.com/w320/mw.png'),
('Malaysia', 'MY', 'https://flagcdn.com/w320/my.png'),
('Maldives', 'MV', 'https://flagcdn.com/w320/mv.png'),
('Mali', 'ML', 'https://flagcdn.com/w320/ml.png'),
('Malta', 'MT', 'https://flagcdn.com/w320/mt.png'),
('Marshall Islands', 'MH', 'https://flagcdn.com/w320/mh.png'),
('Mauritania', 'MR', 'https://flagcdn.com/w320/mr.png'),
('Mauritius', 'MU', 'https://flagcdn.com/w320/mu.png'),
('Mexico', 'MX', 'https://flagcdn.com/w320/mx.png'),
('Micronesia', 'FM', 'https://flagcdn.com/w320/fm.png'),
('Moldova', 'MD', 'https://flagcdn.com/w320/md.png'),
('Monaco', 'MC', 'https://flagcdn.com/w320/mc.png'),
('Mongolia', 'MN', 'https://flagcdn.com/w320/mn.png'),
('Montenegro', 'ME', 'https://flagcdn.com/w320/me.png'),
('Morocco', 'MA', 'https://flagcdn.com/w320/ma.png'),
('Mozambique', 'MZ', 'https://flagcdn.com/w320/mz.png'),
('Myanmar', 'MM', 'https://flagcdn.com/w320/mm.png'),
('Namibia', 'NA', 'https://flagcdn.com/w320/na.png'),
('Nauru', 'NR', 'https://flagcdn.com/w320/nr.png'),
('Nepal', 'NP', 'https://flagcdn.com/w320/np.png'),
('Netherlands', 'NL', 'https://flagcdn.com/w320/nl.png'),
('New Zealand', 'NZ', 'https://flagcdn.com/w320/nz.png'),
('Nicaragua', 'NI', 'https://flagcdn.com/w320/ni.png'),
('Niger', 'NE', 'https://flagcdn.com/w320/ne.png'),
('Nigeria', 'NG', 'https://flagcdn.com/w320/ng.png'),
('North Macedonia', 'MK', 'https://flagcdn.com/w320/mk.png'),
('Norway', 'NO', 'https://flagcdn.com/w320/no.png'),
('Oman', 'OM', 'https://flagcdn.com/w320/om.png'),
('Pakistan', 'PK', 'https://flagcdn.com/w320/pk.png'),
('Palau', 'PW', 'https://flagcdn.com/w320/pw.png'),
('Palestine', 'PS', 'https://flagcdn.com/w320/ps.png'),
('Panama', 'PA', 'https://flagcdn.com/w320/pa.png'),
('Papua New Guinea', 'PG', 'https://flagcdn.com/w320/pg.png'),
('Paraguay', 'PY', 'https://flagcdn.com/w320/py.png'),
('Peru', 'PE', 'https://flagcdn.com/w320/pe.png'),
('Philippines', 'PH', 'https://flagcdn.com/w320/ph.png'),
('Poland', 'PL', 'https://flagcdn.com/w320/pl.png'),
('Portugal', 'PT', 'https://flagcdn.com/w320/pt.png'),
('Qatar', 'QA', 'https://flagcdn.com/w320/qa.png'),
('Romania', 'RO', 'https://flagcdn.com/w320/ro.png'),
('Russia', 'RU', 'https://flagcdn.com/w320/ru.png'),
('Rwanda', 'RW', 'https://flagcdn.com/w320/rw.png'),
('Saint Kitts and Nevis', 'KN', 'https://flagcdn.com/w320/kn.png'),
('Saint Lucia', 'LC', 'https://flagcdn.com/w320/lc.png'),
('Saint Vincent and the Grenadines', 'VC', 'https://flagcdn.com/w320/vc.png'),
('Samoa', 'WS', 'https://flagcdn.com/w320/ws.png'),
('San Marino', 'SM', 'https://flagcdn.com/w320/sm.png'),
('Sao Tome and Principe', 'ST', 'https://flagcdn.com/w320/st.png'),
('Saudi Arabia', 'SA', 'https://flagcdn.com/w320/sa.png'),
('Senegal', 'SN', 'https://flagcdn.com/w320/sn.png'),
('Serbia', 'RS', 'https://flagcdn.com/w320/rs.png'),
('Seychelles', 'SC', 'https://flagcdn.com/w320/sc.png'),
('Sierra Leone', 'SL', 'https://flagcdn.com/w320/sl.png'),
('Singapore', 'SG', 'https://flagcdn.com/w320/sg.png'),
('Slovakia', 'SK', 'https://flagcdn.com/w320/sk.png'),
('Slovenia', 'SI', 'https://flagcdn.com/w320/si.png'),
('Solomon Islands', 'SB', 'https://flagcdn.com/w320/sb.png'),
('Somalia', 'SO', 'https://flagcdn.com/w320/so.png'),
('South Africa', 'ZA', 'https://flagcdn.com/w320/za.png'),
('South Sudan', 'SS', 'https://flagcdn.com/w320/ss.png'),
('Spain', 'ES', 'https://flagcdn.com/w320/es.png'),
('Sri Lanka', 'LK', 'https://flagcdn.com/w320/lk.png'),
('Sudan', 'SD', 'https://flagcdn.com/w320/sd.png'),
('Suriname', 'SR', 'https://flagcdn.com/w320/sr.png'),
('Sweden', 'SE', 'https://flagcdn.com/w320/se.png'),
('Switzerland', 'CH', 'https://flagcdn.com/w320/ch.png'),
('Syria', 'SY', 'https://flagcdn.com/w320/sy.png'),
('Taiwan', 'TW', 'https://flagcdn.com/w320/tw.png'),
('Tajikistan', 'TJ', 'https://flagcdn.com/w320/tj.png'),
('Tanzania', 'TZ', 'https://flagcdn.com/w320/tz.png'),
('Thailand', 'TH', 'https://flagcdn.com/w320/th.png'),
('Togo', 'TG', 'https://flagcdn.com/w320/tg.png'),
('Tonga', 'TO', 'https://flagcdn.com/w320/to.png'),
('Trinidad and Tobago', 'TT', 'https://flagcdn.com/w320/tt.png'),
('Tunisia', 'TN', 'https://flagcdn.com/w320/tn.png'),
('Turkey', 'TR', 'https://flagcdn.com/w320/tr.png'),
('Turkmenistan', 'TM', 'https://flagcdn.com/w320/tm.png'),
('Tuvalu', 'TV', 'https://flagcdn.com/w320/tv.png'),
('Uganda', 'UG', 'https://flagcdn.com/w320/ug.png'),
('Ukraine', 'UA', 'https://flagcdn.com/w320/ua.png'),
('United Arab Emirates', 'AE', 'https://flagcdn.com/w320/ae.png'),
('United Kingdom', 'GB', 'https://flagcdn.com/w320/gb.png'),
('United States', 'US', 'https://flagcdn.com/w320/us.png'),
('Uruguay', 'UY', 'https://flagcdn.com/w320/uy.png'),
('Uzbekistan', 'UZ', 'https://flagcdn.com/w320/uz.png'),
('Vanuatu', 'VU', 'https://flagcdn.com/w320/vu.png'),
('Vatican City', 'VA', 'https://flagcdn.com/w320/va.png'),
('Venezuela', 'VE', 'https://flagcdn.com/w320/ve.png'),
('Vietnam', 'VN', 'https://flagcdn.com/w320/vn.png'),
('Yemen', 'YE', 'https://flagcdn.com/w320/ye.png'),
('Zambia', 'ZM', 'https://flagcdn.com/w320/zm.png'),
('Zimbabwe', 'ZW', 'https://flagcdn.com/w320/zw.png')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    flag_url = EXCLUDED.flag_url,
    updated_at = CURRENT_TIMESTAMP;
